name: haskell-jumble
version: 0.1.0.0
github: 'mayanhavoc/haskell-jumble'
license: BSD3
author: 'mayanhavoc'
maintainer: 'mayanhavoc@gmail.com'
copyright: 'MIT'

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/mayanhavoc/haskell-jumble#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - random

library:
  source-dirs: src

executables:
  jumble:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -dynamic
    dependencies:
      - haskell-jumble

tests:
  haskell-jumble-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-jumble
      - hspec
